/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import calculadora.Calculos;

/**
 *
 * @author José Wilson Grilo
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
    Calculos c = new Calculos();
    private boolean operador1 = true;
    String op = "";
    
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_Painel = new javax.swing.JPanel();
        jL_titulo = new javax.swing.JLabel();
        jB_7 = new javax.swing.JButton();
        jB_8 = new javax.swing.JButton();
        jB_9 = new javax.swing.JButton();
        jB_4 = new javax.swing.JButton();
        jB_5 = new javax.swing.JButton();
        jB_6 = new javax.swing.JButton();
        jB_1 = new javax.swing.JButton();
        jB_2 = new javax.swing.JButton();
        jB_3 = new javax.swing.JButton();
        jTF_mostrar = new javax.swing.JTextField();
        jB_0 = new javax.swing.JButton();
        jB_igual = new javax.swing.JButton();
        jB_somar = new javax.swing.JButton();
        jB_subtrair = new javax.swing.JButton();
        jB_dividir = new javax.swing.JButton();
        jB_multiplicar = new javax.swing.JButton();
        jB_limpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jP_Painel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jL_titulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jL_titulo.setText("Calculadora");

        jB_7.setText("7");
        jB_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_7ActionPerformed(evt);
            }
        });

        jB_8.setText("8");
        jB_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_8ActionPerformed(evt);
            }
        });

        jB_9.setText("9");
        jB_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_9ActionPerformed(evt);
            }
        });

        jB_4.setText("4");
        jB_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_4ActionPerformed(evt);
            }
        });

        jB_5.setText("5");
        jB_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_5ActionPerformed(evt);
            }
        });

        jB_6.setText("6");
        jB_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_6ActionPerformed(evt);
            }
        });

        jB_1.setText("1");
        jB_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_1ActionPerformed(evt);
            }
        });

        jB_2.setText("2");
        jB_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_2ActionPerformed(evt);
            }
        });

        jB_3.setText("3");
        jB_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_3ActionPerformed(evt);
            }
        });

        jB_0.setText("0");
        jB_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_0ActionPerformed(evt);
            }
        });

        jB_igual.setText("=");
        jB_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_igualActionPerformed(evt);
            }
        });

        jB_somar.setText("+");
        jB_somar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_somarActionPerformed(evt);
            }
        });

        jB_subtrair.setText("-");
        jB_subtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_subtrairActionPerformed(evt);
            }
        });

        jB_dividir.setText("/");
        jB_dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_dividirActionPerformed(evt);
            }
        });

        jB_multiplicar.setText("*");
        jB_multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_multiplicarActionPerformed(evt);
            }
        });

        jB_limpar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jB_limpar.setText("Limpar");
        jB_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_limparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_PainelLayout = new javax.swing.GroupLayout(jP_Painel);
        jP_Painel.setLayout(jP_PainelLayout);
        jP_PainelLayout.setHorizontalGroup(
            jP_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_PainelLayout.createSequentialGroup()
                .addGroup(jP_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_PainelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jP_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jP_PainelLayout.createSequentialGroup()
                                .addComponent(jB_4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB_5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB_6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB_subtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jP_PainelLayout.createSequentialGroup()
                                .addComponent(jB_1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB_2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB_3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB_dividir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jP_PainelLayout.createSequentialGroup()
                                .addComponent(jB_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB_0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB_multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jP_PainelLayout.createSequentialGroup()
                                .addComponent(jB_7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB_8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB_9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB_somar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTF_mostrar)))
                    .addGroup(jP_PainelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jL_titulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP_PainelLayout.setVerticalGroup(
            jP_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_PainelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jL_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTF_mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_somar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_subtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_dividir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jP_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jB_0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jB_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jB_multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jB_limpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_Painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_Painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_6ActionPerformed
        // TODO add your handling code here:
        op = op + "6";
        System.out.println(op);
        if(operador1){
            System.out.println("operador 1");
            // ATRIBUI VALORES AO OPERADOR 1
            c.setOpera1(Double.parseDouble(op));
            jTF_mostrar.setText("");
            jTF_mostrar.setText(String.valueOf(c.getOpera1()));
        }else{
            System.out.println("operador 2");
            // ATRIBUI VALORES AO OPERADOR 2
            c.setOpera2(Double.parseDouble(op));
            jTF_mostrar.setText("");
            jTF_mostrar.setText(String.valueOf(c.getOpera1()) + String.valueOf(c.getOperacao()) + String.valueOf(c.getOpera2()));
        }
    }//GEN-LAST:event_jB_6ActionPerformed

    private void jB_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_igualActionPerformed
        // TODO add your handling code here:
        double result;
        // CALCULAR
        result = c.calcular(c.getOpera1(), c.getOpera2(), c.getOperacao());
        jTF_mostrar.setText(String.valueOf(result));
    }//GEN-LAST:event_jB_igualActionPerformed

    private void jB_somarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_somarActionPerformed
        // TODO add your handling code here:
        if(operador1){
            operador1 = false;
            op = "";
        }else{
            operador1 = true;
            op = "";
        }
        
        c.setOperacao('+');
        jTF_mostrar.setText("");
        jTF_mostrar.setText(String.valueOf(c.getOpera1()) + String.valueOf(c.getOperacao()) + String.valueOf(c.getOpera2()));
    }//GEN-LAST:event_jB_somarActionPerformed

    private void jB_subtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_subtrairActionPerformed
        // TODO add your handling code here:
        
        if(operador1){
            operador1 = false;
            op = "";
        }else{
            operador1 = true;
            op = "";
        }
        
        c.setOperacao('-');
        jTF_mostrar.setText("");
        jTF_mostrar.setText(String.valueOf(c.getOpera1()) + String.valueOf(c.getOperacao()) + String.valueOf(c.getOpera2()));
    }//GEN-LAST:event_jB_subtrairActionPerformed

    private void jB_dividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_dividirActionPerformed
        // TODO add your handling code here:
        
        if(operador1){
            operador1 = false;
            op = "";
        }else{
            operador1 = true;
            op = "";
        }
        
        c.setOperacao('/');
        jTF_mostrar.setText("");
        jTF_mostrar.setText(String.valueOf(c.getOpera1()) + String.valueOf(c.getOperacao()) + String.valueOf(c.getOpera2()));
    }//GEN-LAST:event_jB_dividirActionPerformed

    private void jB_multiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_multiplicarActionPerformed
        // TODO add your handling code here:
        
        if(operador1){
            operador1 = false;
            op = "";
        }else{
            operador1 = true;
            op = "";
        }
        
        c.setOperacao('*');
        jTF_mostrar.setText("");
        jTF_mostrar.setText(String.valueOf(c.getOpera1()) + String.valueOf(c.getOperacao()) + String.valueOf(c.getOpera2()));
    }//GEN-LAST:event_jB_multiplicarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:        
    }//GEN-LAST:event_formWindowOpened

    private void jB_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_2ActionPerformed
        // TODO add your handling code here:
        op = op + "2";
        System.out.println(op);
        if(operador1){
            System.out.println("operador 1");
            // ATRIBUI VALORES AO OPERADOR 1
            c.setOpera1(Double.parseDouble(op));
            jTF_mostrar.setText("");
            jTF_mostrar.setText(String.valueOf(c.getOpera1()));
        }else{
            System.out.println("operador 2");
            // ATRIBUI VALORES AO OPERADOR 2
            c.setOpera2(Double.parseDouble(op));
            jTF_mostrar.setText("");
            jTF_mostrar.setText(String.valueOf(c.getOpera1()) + String.valueOf(c.getOperacao()) + String.valueOf(c.getOpera2()));
        }
    }//GEN-LAST:event_jB_2ActionPerformed

    private void jB_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_3ActionPerformed
        // TODO add your handling code here:
        op = op + "3";
        System.out.println(op);
        if(operador1){
            System.out.println("operador 1");
            // ATRIBUI VALORES AO OPERADOR 1
            c.setOpera1(Double.parseDouble(op));
            jTF_mostrar.setText("");
            jTF_mostrar.setText(String.valueOf(c.getOpera1()));
        }else{
            System.out.println("operador 2");
            // ATRIBUI VALORES AO OPERADOR 2
            c.setOpera2(Double.parseDouble(op));
            jTF_mostrar.setText("");
            jTF_mostrar.setText(String.valueOf(c.getOpera1()) + String.valueOf(c.getOperacao()) + String.valueOf(c.getOpera2()));
        }
    }//GEN-LAST:event_jB_3ActionPerformed

    private void jB_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_4ActionPerformed
        // TODO add your handling code here:
        op = op + "4";
        System.out.println(op);
        if(operador1){
            System.out.println("operador 1");
            // ATRIBUI VALORES AO OPERADOR 1
            c.setOpera1(Double.parseDouble(op));
            jTF_mostrar.setText("");
            jTF_mostrar.setText(String.valueOf(c.getOpera1()));
        }else{
            System.out.println("operador 2");
            // ATRIBUI VALORES AO OPERADOR 2
            c.setOpera2(Double.parseDouble(op));
            jTF_mostrar.setText("");
            jTF_mostrar.setText(String.valueOf(c.getOpera1()) + String.valueOf(c.getOperacao()) + String.valueOf(c.getOpera2()));
        }
    }//GEN-LAST:event_jB_4ActionPerformed

    private void jB_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_5ActionPerformed
        // TODO add your handling code here:
        op = op + "5";
        System.out.println(op);
        if(operador1){
            System.out.println("operador 1");
            // ATRIBUI VALORES AO OPERADOR 1
            c.setOpera1(Double.parseDouble(op));
            jTF_mostrar.setText("");
            jTF_mostrar.setText(String.valueOf(c.getOpera1()));
        }else{
            System.out.println("operador 2");
            // ATRIBUI VALORES AO OPERADOR 2
            c.setOpera2(Double.parseDouble(op));
            jTF_mostrar.setText("");
            jTF_mostrar.setText(String.valueOf(c.getOpera1()) + String.valueOf(c.getOperacao()) + String.valueOf(c.getOpera2()));
        }
    }//GEN-LAST:event_jB_5ActionPerformed

    private void jB_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_7ActionPerformed
        // TODO add your handling code here:
        op = op + "7";
        System.out.println(op);
        if(operador1){
            System.out.println("operador 1");
            // ATRIBUI VALORES AO OPERADOR 1
            c.setOpera1(Double.parseDouble(op));
            jTF_mostrar.setText("");
            jTF_mostrar.setText(String.valueOf(c.getOpera1()));
        }else{
            System.out.println("operador 2");
            // ATRIBUI VALORES AO OPERADOR 2
            c.setOpera2(Double.parseDouble(op));
            jTF_mostrar.setText("");
            jTF_mostrar.setText(String.valueOf(c.getOpera1()) + String.valueOf(c.getOperacao()) + String.valueOf(c.getOpera2()));
        }
    }//GEN-LAST:event_jB_7ActionPerformed

    private void jB_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_8ActionPerformed
        // TODO add your handling code here:
        op = op + "8";
        System.out.println(op);
        if(operador1){
            System.out.println("operador 1");
            // ATRIBUI VALORES AO OPERADOR 1
            c.setOpera1(Double.parseDouble(op));
            jTF_mostrar.setText("");
            jTF_mostrar.setText(String.valueOf(c.getOpera1()));
        }else{
            System.out.println("operador 2");
            // ATRIBUI VALORES AO OPERADOR 2
            c.setOpera2(Double.parseDouble(op));
            jTF_mostrar.setText("");
            jTF_mostrar.setText(String.valueOf(c.getOpera1()) + String.valueOf(c.getOperacao()) + String.valueOf(c.getOpera2()));
        }
    }//GEN-LAST:event_jB_8ActionPerformed

    private void jB_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_9ActionPerformed
        // TODO add your handling code here:
        op = op + "9";
        System.out.println(op);
        if(operador1){
            System.out.println("operador 1");
            // ATRIBUI VALORES AO OPERADOR 1
            c.setOpera1(Double.parseDouble(op));
            jTF_mostrar.setText("");
            jTF_mostrar.setText(String.valueOf(c.getOpera1()));
        }else{
            System.out.println("operador 2");
            // ATRIBUI VALORES AO OPERADOR 2
            c.setOpera2(Double.parseDouble(op));
            jTF_mostrar.setText("");
            jTF_mostrar.setText(String.valueOf(c.getOpera1()) + String.valueOf(c.getOperacao()) + String.valueOf(c.getOpera2()));
        }
    }//GEN-LAST:event_jB_9ActionPerformed

    private void jB_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_0ActionPerformed
        // TODO add your handling code here:
        op = op + "0";
        System.out.println(op);
        if(operador1){
            System.out.println("operador 1");
            // ATRIBUI VALORES AO OPERADOR 1
            c.setOpera1(Double.parseDouble(op));
            jTF_mostrar.setText("");
            jTF_mostrar.setText(String.valueOf(c.getOpera1()));
        }else{
            System.out.println("operador 2");
            // ATRIBUI VALORES AO OPERADOR 2
            c.setOpera2(Double.parseDouble(op));
            jTF_mostrar.setText("");
            jTF_mostrar.setText(String.valueOf(c.getOpera1()) + String.valueOf(c.getOperacao()) + String.valueOf(c.getOpera2()));
        }
    }//GEN-LAST:event_jB_0ActionPerformed

    private void jB_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_1ActionPerformed
        // TODO add your handling code here:
        op = op + "1";
        System.out.println(op);
        if(operador1){
            System.out.println("operador 1");
            // ATRIBUI VALORES AO OPERADOR 1
            c.setOpera1(Double.parseDouble(op));
            jTF_mostrar.setText("");
            jTF_mostrar.setText(String.valueOf(c.getOpera1()));
        }else{
            System.out.println("operador 2");
            // ATRIBUI VALORES AO OPERADOR 2
            c.setOpera2(Double.parseDouble(op));
            jTF_mostrar.setText("");
            jTF_mostrar.setText(String.valueOf(c.getOpera1()) + String.valueOf(c.getOperacao()) + String.valueOf(c.getOpera2()));
        }
    }//GEN-LAST:event_jB_1ActionPerformed

    private void jB_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_limparActionPerformed
        // TODO add your handling code here:
        op = "";
        operador1 = true;
        jTF_mostrar.setText("");
        c.setOpera1(0);
        c.setOpera2(0);
        c.setOperacao(' ');
    }//GEN-LAST:event_jB_limparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Principal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_0;
    private javax.swing.JButton jB_1;
    private javax.swing.JButton jB_2;
    private javax.swing.JButton jB_3;
    private javax.swing.JButton jB_4;
    private javax.swing.JButton jB_5;
    private javax.swing.JButton jB_6;
    private javax.swing.JButton jB_7;
    private javax.swing.JButton jB_8;
    private javax.swing.JButton jB_9;
    private javax.swing.JButton jB_dividir;
    private javax.swing.JButton jB_igual;
    private javax.swing.JButton jB_limpar;
    private javax.swing.JButton jB_multiplicar;
    private javax.swing.JButton jB_somar;
    private javax.swing.JButton jB_subtrair;
    private javax.swing.JLabel jL_titulo;
    private javax.swing.JPanel jP_Painel;
    private javax.swing.JTextField jTF_mostrar;
    // End of variables declaration//GEN-END:variables
}
